# Objectif : Angular + nodejs + mariadb + mongoDB | Objective: Test angular + nodejs + mariadb + mongoDB

services:
  mariadb:
    image: mariadb:11.7.2
    container_name: cinephoria-sqldb
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - cinephoria-network

  mongo:
    image: mongo:8.0
    container_name: cinephoria-nosqldb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_URI=${MONGO_URI}
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./nosql/init:/docker-entrypoint-initdb.d/*.js:ro
    networks:
      - cinephoria-network

  cinephoria-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: app-backend
    container_name: cinephoria-back
    restart: on-failure
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - mariadb
      - mongo
    networks:
      - cinephoria-network
    stdin_open: true
    tty: true

  cinephoria-front:
    build:
      context: .
      dockerfile: projects/cinephoria-web/Dockerfile
    image: app-frontend
    container_name: cinephoria-front
    restart: always
    ports:
      - "8081:80"
    environment:
      - API_URL=${API_URL}
    depends_on:
      - cinephoria-back
    networks:
      - cinephoria-network

  cinephoria-test:
      build:
        context: .
        dockerfile: Dockerfile
      image: app-test
      container_name: cinephoria-test
      restart: on-failure
      environment:
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - MARIADB_HOST=${MARIADB_HOST}
        - MARIADB_PORT=${MARIADB_PORT}
        - DATABASE_URL=${DATABASE_URL}
        - MONGO_NAME=${MONGO_NAME}
        - MONGO_USERNAME=${MONGO_USERNAME}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - MONGO_HOST=${MONGO_HOST}
        - MONGO_PORT=${MONGO_PORT}
        - MONGO_URI=${MONGO_URI}
        - JWT_SECRET=${JWT_SECRET}
        - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
        - CORS_ORIGIN=${CORS_ORIGIN}
        - COOKIE_SECRET=${COOKIE_SECRET}
        - PORT=${PORT}
        - BASE_URL=${BASE_URL}
      volumes:
        - .:/app
        - /app/node_modules
      depends_on:
        - cinephoria-back
        - cinephoria-front
      networks:
        - cinephoria-network
      tty: true
      stdin_open: true

networks:
  cinephoria-network:
    driver: bridge

volumes:
  mariadb_data:
  mongo_data: