# Objectif : Staging production cinephoria application using nginx + angular + nodejs + mariadb + mongoDB
# Kindly note that the creation of a new accounts and logins will not work for this as it is in a docker contained environment with no access to the smtp provider
# Created to test other pre-production elements such as database connections, ssl, nginx, angular, nodejs, docker, volumes, networks, etc...

# NOTE ! FOR PRODUCTION THE INITIALIZED USERS SHOULD BE REMOVED EITHER FROM THE SQL 02_init_data FILE OR THE
# DATABASE DIRECTLY TO AVOID SECURITY BREACHES !

services:
  mariadb:
    build:
      context: ./sql
      dockerfile: Dockerfile
    container_name: cinephoria-sqldb
    restart: unless-stopped
    # env_file: ".env" # Uncomment for local use only, comment for commits
    environment:
      - TZ=Europe/Paris
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - SUPER_ADMIN=${SUPER_ADMIN}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d:ro
      - mariadb_backup:/backup
    networks:
      - cinephoria-network

  mongo:
    image: mongo:8.0
    container_name: cinephoria-nosqldb
    restart: unless-stopped
    # env_file: ".env" # Uncomment for local use only, comment for commits
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./nosql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - cinephoria-network

  cinephoria-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: app-backend
    container_name: cinephoria-back
    restart: on-failure
    ports:
      - "3001:3000"
    # env_file: ".env" # Uncomment for local use only, comment for commits
    environment:
      - NODE_ENV=${NODE_ENV}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - PORT=${PORT}
      - API_URL=${API_URL}
      - BASE_URL=${BASE_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - EMPLOYEE_EMAIL=${EMPLOYEE_EMAIL}
      - EMPLOYEE_USERNAME=${EMPLOYEE_USERNAME}
      - EMPLOYEE_PASSWORD=${EMPLOYEE_PASSWORD}
      - DB_SSL=${DB_SSL}
    depends_on:
      - mariadb
      - mongo
    networks:
      - cinephoria-network  
      
  cinephoria-front:
    build:
      context: .
      dockerfile: projects/cinephoria-web/Dockerfile.staging
    image: app-frontend
    container_name: cinephoria-front
    restart: always
    ports:
      - "8081:80"
    # env_file: ".env" # Uncomment for local use only, comment for commits
    environment:
      - API_URL=${API_URL}
    depends_on:
      - cinephoria-back
    networks:
      - cinephoria-network

networks:
  cinephoria-network:
    driver: bridge

volumes:
  mariadb_data:
  mariadb_backup:
  mongo_data: